# Generated by Django 3.2.12 on 2022-02-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='attributestitles',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Название атрибута', 'verbose_name_plural': 'Название атрибутов'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='deliveriesstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Статус доставки', 'verbose_name_plural': 'Статусы доставок'},
        ),
        migrations.AlterModelOptions(
            name='deliveriestype',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Наименование доставки', 'verbose_name_plural': 'Наименовании доставок'},
        ),
        migrations.AlterModelOptions(
            name='discounts',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='makerofproducts',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Призводитель', 'verbose_name_plural': 'Призводители'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ordersdetails',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Список заказа', 'verbose_name_plural': 'Списки заказов'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsdiscounts',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Товар со скидкой', 'verbose_name_plural': 'Товары со скидками'},
        ),
        migrations.AlterModelOptions(
            name='productsimages',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Картина товара', 'verbose_name_plural': 'Картины товаров'},
        ),
        migrations.AlterModelOptions(
            name='ratetypes',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.AlterModelOptions(
            name='taxes',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='usersstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Статус пользователя', 'verbose_name_plural': 'Статусы пользователей'},
        ),
        migrations.AlterField(
            model_name='attributes',
            name='attribute_title_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.attributestitles', verbose_name='Название аттрибута'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='rate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ratetypes', verbose_name='Тип значение скидки'),
        ),
        migrations.AlterField(
            model_name='makerofproducts',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.countries', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliveriestype', verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliveriesstatus', verbose_name='Статус доставки'),
        ),
        migrations.AlterField(
            model_name='ordersdetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orders', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='ordersdetails',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productsimages', verbose_name='Главная картина'),
        ),
        migrations.AlterField(
            model_name='products',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.makerofproducts', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='markup_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ratetypes', verbose_name='Тип надбавки'),
        ),
        migrations.AlterField(
            model_name='productsdiscounts',
            name='discount_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.discounts', verbose_name='свойство cкидка'),
        ),
        migrations.AlterField(
            model_name='productsdiscounts',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='rate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ratetypes', verbose_name='Тип значение налога'),
        ),
    ]
