# Generated by Django 3.2.12 on 2022-02-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220226_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.productsimages', verbose_name='Главная картина'),
        ),
    ]
