# Generated by Django 3.2.12 on 2022-02-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_products_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetypes',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug название'),
        ),
        migrations.AlterField(
            model_name='products',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productsimages', verbose_name='Главная картина'),
        ),
    ]
