# Generated by Django 3.2.12 on 2022-02-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220226_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetypes',
            name='slug',
            field=models.SlugField(verbose_name='Slug название'),
        ),
    ]
